name: Print Environment Variables

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the 'main' branch

env:
  GLOBAL_VAR: global value

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use environment variables
        env:
          STEP_VAR: ${{ env.GLOBAL_VAR }} - step specific
        run: |
          echo $GLOBAL_VAR
          echo $JOB_VAR
          echo $STEP_VAR



