name: Print Environment Variables

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the 'main' branch

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://api.example.com
      API_VERSION: v1
    steps:
      - name: Set derived environment variable
        env:
          FULL_API_URL: ${{ env.BASE_URL }}/${{ env.API_VERSION }}
        run: echo $FULL_API_URL


