name: Print Environment Variables

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the 'main' branch

env:
  FIRST_NAME: John
  LAST_NAME: Doe

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set full name
        run: echo "FULL_NAME=${{ env.FIRST_NAME }} ${{ env.LAST_NAME }}" >> $GITHUB_ENV
