name: Print Environment Variables

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the 'main' branch

env:
  FIRST_NAME: John

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello ${{ env.FIRST_NAME }}"  # This also works!
    steps:
      - name: Print names
        run: |
          echo $FULL_NAME
          echo $GREETING

